### ISSUE TITLE
Add ability to configure how Spakr handles dates in parquet files.

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#2175]
## Background
With Spark 3 new option were added how to work with dates pre 1900 in parquet files
The settings are:
`spark.sql.parquet.datetimeRebaseModeInRead`
`spark.sql.parquet.datetimeRebaseModeInWrite`
`spark.sql.parquet.int96RebaseModeInRead`
`spark.sql.parquet.int96RebaseModeInWrite`

[Details here](https://spark.apache.org/docs/3.2.0/sql-data-sources-parquet.html).

## Feature
Allow setting of the options for Enceladus jobs
```[tasklist]
### Tasks
- [ ] Add command line options to be able to set the **read** options. Set a default behavior either to `EXCEPTION` or `LEGACY`.
- [ ] Modify the helper scripts to recognize these settings
- [ ] Add an `reference.conf`/`application.conf` setting to be applied to write options. The default should be `LEGACY`
```

## To discuss
* The command line option names
* The command line defaults
* The write configuration names

**Comment by miroslavpojer** [comment]
This behaviour can be reached by adding:
`--conf spark.sql.parquet.datetimeRebaseModeInRead=LEGACY --conf spark.sql.parquet.datetimeRebaseModeInWrite=LEGACY --conf spark.sql.parquet.int96RebaseModeInRead=LEGACY --conf spark.sql.parquet.int96RebaseModeInWrite=LEGACY`
into spark job json file call `"spark-submit": "spark-submit --num-executors 2 --executor-memory 2G --deploy-mode client --conf spark.sql.parquet.datetimeRebaseModeInRead=LEGACY --conf spark.sql.parquet.datetimeRebaseModeInWrite=LEGACY --conf spark.sql.parquet.int96RebaseModeInRead=LEGACY --conf spark.sql.parquet.int96RebaseModeInWrite=LEGACY",`

**Comment by benedeki** [comment]
> This behaviour can be reached by adding: `--conf spark.sql.parquet.datetimeRebaseModeInRead=LEGACY --conf spark.sql.parquet.datetimeRebaseModeInWrite=LEGACY` into spark job json file call `"spark-submit": "spark-submit --num-executors 2 --executor-memory 2G --deploy-mode client --conf spark.sql.parquet.datetimeRebaseModeInRead=LEGACY --conf spark.sql.parquet.datetimeRebaseModeInWrite=LEGACY",`
> 
> No code changes in Enceladus are needed. See example usage in json [file](https://github.com/AbsaOSS/enceladus/blob/develop/examples/data/e2e_tests/test_jsons/stdNfDnTest.json).

Great finding and solution. So only the Helper scripts needs to be enhanced.

**Comment by miroslavpojer** [comment]
> Yes
