### ISSUE TITLE
Execute Enceladus application data backup and restore

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#2221]
## Background [Optional]
A clear explanation of the reason for raising the question. 
This gives us a better understanding of your use cases and how we might accommodate them.

## Goald
TBD

```[tasklist]
### Tasks
- [ ] Create production change
- [ ] Confirm BU&R date
- [ ] Schedule SNOW change
- [ ] Get Approval
- [x] Execute BU&R
- [x] Submit BU&R evidence
```

**Comment by ABHM721** [comment]
The actual BU&R activity depends on how backup environments are managed.
Two potential options spring to mind:
- a new DB running alongside the existing DB, using a backup of the existing DB
- an isolated environment, also using a backup of the existing DB

Procedure in either case:
- Select one Menas environment from which to test BU&R (in the case of 3 machines, for example, the third)
- Limit access to those doing the BU&R test so potential users are not inadvertently accessing the instance connected to the backup DB
- Point the Menas env at the backup DB
- Update Enceladus configs (perhaps in an isolated env with fresh configs) to point to the selected Menas environment
- Verify data is as expected on the Menas env
- Perhaps run a test job from Enceladus to verify no issues with the backup DB, etc

After testing is concluded:
- Point Menas at the original DB
- Return normal access for users
- Revert Enceladus configs if changed

This is more a test of the backup rather than Menas/Enceladus, as nothing major is changed there.
Verification of the data is the goal - be it count of items, data integrity, normal functioning of the DB, etc.

**Comment by zakera786** [comment]
We need to be clear on how we are validating the data is landing as expected for example are we making a copy of last night's data that landed and today we spin up the backup and restore and run that same pipeline and see if the data matches ? We need data test proof for this task

**Comment by zakera786** [comment]
[Backup Restoration Evidence Checklist v3.6.docx](https://github.com/user-attachments/files/17057530/Backup.Restoration.Evidence.Checklist.v3.6.docx)

**Comment by miroslavpojer** [comment]
> [Backup Restoration Evidence Checklist v3.6.docx](https://github.com/user-attachments/files/17057530/Backup.Restoration.Evidence.Checklist.v3.6.docx)

I am missing for how long the backups have to be stored. Or is that about keep only the latest one?

**Comment by dk1844** [comment]
I have added pre- and post- counting/hash script results in the section _Recovery Point Validation_.
